# Generated by Django 3.1.7 on 2021-03-16 21:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterField(
            model_name='bike',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bikes', to='products.category'),
        ),
        migrations.AlterField(
            model_name='bikeimages',
            name='bike',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='images', to='products.bike'),
        ),
    ]
